server:
  port: 8081

spring:
  kafka:
    bootstrapAddress: broker-analyzer:29092
    topic:
      payments: payments
      suspicious-payments: suspicious-payments
      checked-payments: checked-payments
    consumer:
      groupId: analyzer-group-id

redis:
  hostName: redis-analyzer
  port: 6379

feign:
  hystrix:
    enabled: true