server:
  port: 8081

spring:
  kafka:
    bootstrapAddress: localhost:9092
    topic:
      payments: payments
      suspicious-payments: suspicious-payments
      checked-payments: checked-payments
    consumer:
      groupId: analyzer-group-id

feign:
  hystrix:
    enabled: true